UPDATE finalHist SET logoPNG = "Aberdeen_IronBirds.png" WHERE tmName = "Aberdeen IronBirds";
UPDATE finalHist SET logoPNG = "Aguascalientes_Rieleros.png" WHERE tmName = "Aguascalientes Rieleros";
UPDATE finalHist SET logoPNG = "Akron_Aeros.png" WHERE tmName = "Akron Aeros";
UPDATE finalHist SET logoPNG = "Akron_RubberDucks.png" WHERE tmName = "Akron RubberDucks";
UPDATE finalHist SET logoPNG = "Albany-Colonie_Yankees.png" WHERE tmName = "Albany-Colonie Yankees";
UPDATE finalHist SET logoPNG = "Albuquerque_Dukes.png" WHERE tmName = "Albuquerque Dukes";
UPDATE finalHist SET logoPNG = "Albuquerque_Isotopes.png" WHERE tmName = "Albuquerque Isotopes";
UPDATE finalHist SET logoPNG = "Altoona_Curve.png" WHERE tmName = "Altoona Curve";
UPDATE finalHist SET logoPNG = "Amarillo_Sod_Poodles.png" WHERE tmName = "Amarillo Sod Poodles";
UPDATE finalHist SET logoPNG = "Arkansas_Travelers.png" WHERE tmName = "Arkansas Travelers";
UPDATE finalHist SET logoPNG = "Asheville_Tourists.png" WHERE tmName = "Asheville Tourists";
UPDATE finalHist SET logoPNG = "Auburn_Doubledays.png" WHERE tmName = "Auburn Doubledays";
UPDATE finalHist SET logoPNG = "Augusta_Greenjackets.png" WHERE tmName = "Augusta Greenjackets";
UPDATE finalHist SET logoPNG = "Bakersfield_Blaze.png" WHERE tmName = "Bakersfield Blaze";
UPDATE finalHist SET logoPNG = "Batavia_Muckdogs.png" WHERE tmName = "Batavia Muckdogs";
UPDATE finalHist SET logoPNG = "Beloit_Snappers.png" WHERE tmName = "Beloit Snappers";
UPDATE finalHist SET logoPNG = "Billings_Mustangs.png" WHERE tmName = "Billings Mustangs";
UPDATE finalHist SET logoPNG = "Biloxi_Shuckers.png" WHERE tmName = "Biloxi Shuckers";
UPDATE finalHist SET logoPNG = "Binghamton_Mets.png" WHERE tmName = "Binghamton Mets";
UPDATE finalHist SET logoPNG = "Binghamton_Rumble_Ponies.png" WHERE tmName = "Binghamton Rumble Ponies";
UPDATE finalHist SET logoPNG = "Birmingham_Barons.png" WHERE tmName = "Birmingham Barons";
UPDATE finalHist SET logoPNG = "Bluefield_Blue_Jays.png" WHERE tmName = "Bluefield Blue Jays";
UPDATE finalHist SET logoPNG = "Bluefield_Orioles.png" WHERE tmName = "Bluefield Orioles";
UPDATE finalHist SET logoPNG = "Boise_Hawks.png" WHERE tmName = "Boise Hawks";
UPDATE finalHist SET logoPNG = "Bowie_BaySox.png" WHERE tmName = "Bowie BaySox";
UPDATE finalHist SET logoPNG = "Bowling_Green_Hot_Rods.png" WHERE tmName = "Bowling Green Hot Rods";
UPDATE finalHist SET logoPNG = "Bradenton_Marauders.png" WHERE tmName = "Bradenton Marauders";
UPDATE finalHist SET logoPNG = "Brevard_County_Manatees.png" WHERE tmName = "Brevard County Manatees";
UPDATE finalHist SET logoPNG = "Bristol_Pirates.png" WHERE tmName = "Bristol Pirates";
UPDATE finalHist SET logoPNG = "Bristol_White_Sox.png" WHERE tmName = "Bristol White Sox";
UPDATE finalHist SET logoPNG = "Brooklyn_Cyclones.png" WHERE tmName = "Brooklyn Cyclones";
UPDATE finalHist SET logoPNG = "Buffalo_Bisons.png" WHERE tmName = "Buffalo Bisons";
UPDATE finalHist SET logoPNG = "Buies_Creek_Astros.png" WHERE tmName = "Buies Creek Astros";
UPDATE finalHist SET logoPNG = "Burlington_Bees.png" WHERE tmName = "Burlington Bees";
UPDATE finalHist SET logoPNG = "Burlington_Royals.png" WHERE tmName = "Burlington Royals";
UPDATE finalHist SET logoPNG = "Calgary_Cannons.png" WHERE tmName = "Calgary Cannons";
UPDATE finalHist SET logoPNG = "Campeche_Piratas.png" WHERE tmName = "Campeche Piratas";
UPDATE finalHist SET logoPNG = "Canton-Akron_Indians.png" WHERE tmName = "Canton-Akron Indians";
UPDATE finalHist SET logoPNG = "Capital_City_Bombers.png" WHERE tmName = "Capital City Bombers";
UPDATE finalHist SET logoPNG = "Carmen_Delfines.png" WHERE tmName = "Carmen Delfines";
UPDATE finalHist SET logoPNG = "Carolina_Mudcats.png" WHERE tmName = "Carolina Mudcats";
UPDATE finalHist SET logoPNG = "Casper_Ghosts.png" WHERE tmName = "Casper Ghosts";
UPDATE finalHist SET logoPNG = "Casper_Rockies.png" WHERE tmName = "Casper Rockies";
UPDATE finalHist SET logoPNG = "Cedar_Rapids_Kernels.png" WHERE tmName = "Cedar Rapids Kernels";
UPDATE finalHist SET logoPNG = "Charleston_Alley_Cats.png" WHERE tmName = "Charleston Alley Cats";
UPDATE finalHist SET logoPNG = "Charleston_Charlies.png" WHERE tmName = "Charleston Charlies";
UPDATE finalHist SET logoPNG = "Charleston_Riverdogs.png" WHERE tmName = "Charleston Riverdogs";
UPDATE finalHist SET logoPNG = "Charlotte_Knights.png" WHERE tmName = "Charlotte Knights";
UPDATE finalHist SET logoPNG = "Charlotte_Rangers.png" WHERE tmName = "Charlotte Rangers";
UPDATE finalHist SET logoPNG = "Charlotte_StoneCrabs.png" WHERE tmName = "Charlotte StoneCrabs";
UPDATE finalHist SET logoPNG = "Chattanooga_Lookouts.png" WHERE tmName = "Chattanooga Lookouts";
UPDATE finalHist SET logoPNG = "Chihuahua_Dorados.png" WHERE tmName = "Chihuahua Dorados";
UPDATE finalHist SET logoPNG = "Clearwater_Threshers.png" WHERE tmName = "Clearwater Threshers";
UPDATE finalHist SET logoPNG = "Clinton_Lumberkings.png" WHERE tmName = "Clinton Lumberkings";
UPDATE finalHist SET logoPNG = "Colorado_Springs_Sky_Sox.png" WHERE tmName = "Colorado Springs Sky Sox";
UPDATE finalHist SET logoPNG = "Columbia_Fireflies.png" WHERE tmName = "Columbia Fireflies";
UPDATE finalHist SET logoPNG = "Columbus_Catfish.png" WHERE tmName = "Columbus Catfish";
UPDATE finalHist SET logoPNG = "Columbus_Clippers.png" WHERE tmName = "Columbus Clippers";
UPDATE finalHist SET logoPNG = "Columbus_Jets.png" WHERE tmName = "Columbus Jets";
UPDATE finalHist SET logoPNG = "Columbus_RedStixx.png" WHERE tmName = "Columbus RedStixx";
UPDATE finalHist SET logoPNG = "Connecticut_Defenders.png" WHERE tmName = "Connecticut Defenders";
UPDATE finalHist SET logoPNG = "Connecticut_Tigers.png" WHERE tmName = "Connecticut Tigers";
UPDATE finalHist SET logoPNG = "Corpus_Christi_Hooks.png" WHERE tmName = "Corpus Christi Hooks";
UPDATE finalHist SET logoPNG = "Danville_97s.png" WHERE tmName = "Danville 97s";
UPDATE finalHist SET logoPNG = "Danville_Braves.png" WHERE tmName = "Danville Braves";
UPDATE finalHist SET logoPNG = "Dayton_Dragons.png" WHERE tmName = "Dayton Dragons";
UPDATE finalHist SET logoPNG = "Daytona_Cubs.png" WHERE tmName = "Daytona Cubs";
UPDATE finalHist SET logoPNG = "Daytona_Tortugas.png" WHERE tmName = "Daytona Tortugas";
UPDATE finalHist SET logoPNG = "Delmarva_Shorebirds.png" WHERE tmName = "Delmarva Shorebirds";
UPDATE finalHist SET logoPNG = "Denver_Zephyrs.png" WHERE tmName = "Denver Zephyrs";
UPDATE finalHist SET logoPNG = "Down_East_Wood_Ducks.png" WHERE tmName = "Down East Wood Ducks";
UPDATE finalHist SET logoPNG = "Dunedin_Blue_Jays.png" WHERE tmName = "Dunedin Blue Jays";
UPDATE finalHist SET logoPNG = "Durham_Bulls.png" WHERE tmName = "Durham Bulls";
UPDATE finalHist SET logoPNG = "Edmonton_Trappers.png" WHERE tmName = "Edmonton Trappers";
UPDATE finalHist SET logoPNG = "El_Paso_Chihuahuas.png" WHERE tmName = "El Paso Chihuahuas";
UPDATE finalHist SET logoPNG = "El_Paso_Diablos.png" WHERE tmName = "El Paso Diablos";
UPDATE finalHist SET logoPNG = "Elizabethton_Twins.png" WHERE tmName = "Elizabethton Twins";
UPDATE finalHist SET logoPNG = "Erie_SeaWolves.png" WHERE tmName = "Erie SeaWolves";
UPDATE finalHist SET logoPNG = "Eugene_Emeralds.png" WHERE tmName = "Eugene Emeralds";
UPDATE finalHist SET logoPNG = "Evansville_Triplets.png" WHERE tmName = "Evansville Triplets";
UPDATE finalHist SET logoPNG = "Everett_AquaSox.png" WHERE tmName = "Everett AquaSox";
UPDATE finalHist SET logoPNG = "Fayetteville_Woodpeckers.png" WHERE tmName = "Fayetteville Woodpeckers";
UPDATE finalHist SET logoPNG = "Florida_Fire_Frogs.png" WHERE tmName = "Florida Fire Frogs";
UPDATE finalHist SET logoPNG = "Fort_Myers_Miracle.png" WHERE tmName = "Fort Myers Miracle";
UPDATE finalHist SET logoPNG = "Fort_Wayne_Tincaps.png" WHERE tmName = "Fort Wayne Tincaps";
UPDATE finalHist SET logoPNG = "Fort_Wayne_Wizards.png" WHERE tmName = "Fort Wayne Wizards";
UPDATE finalHist SET logoPNG = "Frederick_Keys.png" WHERE tmName = "Frederick Keys";
UPDATE finalHist SET logoPNG = "Fresno_Grizzlies.png" WHERE tmName = "Fresno Grizzlies";
UPDATE finalHist SET logoPNG = "Frisco_RoughRiders.png" WHERE tmName = "Frisco RoughRiders";
UPDATE finalHist SET logoPNG = "Grand_Junction_Rockies.png" WHERE tmName = "Grand Junction Rockies";
UPDATE finalHist SET logoPNG = "Great_Falls_Voyagers.png" WHERE tmName = "Great Falls Voyagers";
UPDATE finalHist SET logoPNG = "Great_Falls_White_Sox.png" WHERE tmName = "Great Falls White Sox";
UPDATE finalHist SET logoPNG = "Great_Lakes_Loons.png" WHERE tmName = "Great Lakes Loons";
UPDATE finalHist SET logoPNG = "Greeneville_Astros.png" WHERE tmName = "Greeneville Astros";
UPDATE finalHist SET logoPNG = "Greeneville_Reds.png" WHERE tmName = "Greeneville Reds";
UPDATE finalHist SET logoPNG = "Greensboro_Bats.png" WHERE tmName = "Greensboro Bats";
UPDATE finalHist SET logoPNG = "Greensboro_Grasshoppers.png" WHERE tmName = "Greensboro Grasshoppers";
UPDATE finalHist SET logoPNG = "Greensboro_Hornets.png" WHERE tmName = "Greensboro Hornets";
UPDATE finalHist SET logoPNG = "Greenville_Bombers.png" WHERE tmName = "Greenville Bombers";
UPDATE finalHist SET logoPNG = "Greenville_Braves.png" WHERE tmName = "Greenville Braves";
UPDATE finalHist SET logoPNG = "Greenville_Drive.png" WHERE tmName = "Greenville Drive";
UPDATE finalHist SET logoPNG = "Gwinnett_Braves.png" WHERE tmName = "Gwinnett Braves";
UPDATE finalHist SET logoPNG = "Gwinnett_Stripers.png" WHERE tmName = "Gwinnett Stripers";
UPDATE finalHist SET logoPNG = "Hagerstown_Suns.png" WHERE tmName = "Hagerstown Suns";
UPDATE finalHist SET logoPNG = "Hardware_City_Rock_Cats.png" WHERE tmName = "Hardware City Rock Cats";
UPDATE finalHist SET logoPNG = "Harrisburg_Senators.png" WHERE tmName = "Harrisburg Senators";
UPDATE finalHist SET logoPNG = "Hartford_Yard_Goats.png" WHERE tmName = "Hartford Yard Goats";
UPDATE finalHist SET logoPNG = "Helena_Brewers.png" WHERE tmName = "Helena Brewers";
UPDATE finalHist SET logoPNG = "Hickory_Crawdads.png" WHERE tmName = "Hickory Crawdads";
UPDATE finalHist SET logoPNG = "High_Desert_Mavericks.png" WHERE tmName = "High Desert Mavericks";
UPDATE finalHist SET logoPNG = "Hillsboro_Hops.png" WHERE tmName = "Hillsboro Hops";
UPDATE finalHist SET logoPNG = "Hudson_Valley_Renegades.png" WHERE tmName = "Hudson Valley Renegades";
UPDATE finalHist SET logoPNG = "Huntsville_Stars.png" WHERE tmName = "Huntsville Stars";
UPDATE finalHist SET logoPNG = "Idaho_Falls_Chukars.png" WHERE tmName = "Idaho Falls Chukars";
UPDATE finalHist SET logoPNG = "Indianapolis_Indians.png" WHERE tmName = "Indianapolis Indians";
UPDATE finalHist SET logoPNG = "Inland_Empire_66ers.png" WHERE tmName = "Inland Empire 66ers";
UPDATE finalHist SET logoPNG = "Iowa_Cubs.png" WHERE tmName = "Iowa Cubs";
UPDATE finalHist SET logoPNG = "Iowa_Oaks.png" WHERE tmName = "Iowa Oaks";
UPDATE finalHist SET logoPNG = "Jackson_Generals.png" WHERE tmName = "Jackson Generals";
UPDATE finalHist SET logoPNG = "Jacksonville_Expos.png" WHERE tmName = "Jacksonville Expos";
UPDATE finalHist SET logoPNG = "Jacksonville_Jumbo_Shrimp.png" WHERE tmName = "Jacksonville Jumbo Shrimp";
UPDATE finalHist SET logoPNG = "Jacksonville_Suns.png" WHERE tmName = "Jacksonville Suns";
UPDATE finalHist SET logoPNG = "Jamestown_Jammers.png" WHERE tmName = "Jamestown Jammers";
UPDATE finalHist SET logoPNG = "Johnson_City_Cardinals.png" WHERE tmName = "Johnson City Cardinals";
UPDATE finalHist SET logoPNG = "Jupiter_Hammerheads.png" WHERE tmName = "Jupiter Hammerheads";
UPDATE finalHist SET logoPNG = "Kane_County_Cougars.png" WHERE tmName = "Kane County Cougars";
UPDATE finalHist SET logoPNG = "Kannapolis_Intimidators.png" WHERE tmName = "Kannapolis Intimidators";
UPDATE finalHist SET logoPNG = "Kingsport_Mets.png" WHERE tmName = "Kingsport Mets";
UPDATE finalHist SET logoPNG = "Kinston_Indians.png" WHERE tmName = "Kinston Indians";
UPDATE finalHist SET logoPNG = "Laguna_Vaqueros.png" WHERE tmName = "Laguna Vaqueros";
UPDATE finalHist SET logoPNG = "Lake_County_Captains.png" WHERE tmName = "Lake County Captains";
UPDATE finalHist SET logoPNG = "Lake_Elsinore_Storm.png" WHERE tmName = "Lake Elsinore Storm";
UPDATE finalHist SET logoPNG = "Lakeland_Flying_Tigers.png" WHERE tmName = "Lakeland Flying Tigers";
UPDATE finalHist SET logoPNG = "Lakeland_Tigers.png" WHERE tmName = "Lakeland Tigers";
UPDATE finalHist SET logoPNG = "Lakewood_BlueClaws.png" WHERE tmName = "Lakewood BlueClaws";
UPDATE finalHist SET logoPNG = "Lancaster_Jethawks.png" WHERE tmName = "Lancaster Jethawks";
UPDATE finalHist SET logoPNG = "Lansing_Lugnuts.png" WHERE tmName = "Lansing Lugnuts";
UPDATE finalHist SET logoPNG = "Las_Vegas_51s.png" WHERE tmName = "Las Vegas 51s";
UPDATE finalHist SET logoPNG = "Las_Vegas_Aviators.png" WHERE tmName = "Las Vegas Aviators";
UPDATE finalHist SET logoPNG = "Lehigh_Valley_IronPigs.png" WHERE tmName = "Lehigh Valley IronPigs";
UPDATE finalHist SET logoPNG = "Lexington_Legends.png" WHERE tmName = "Lexington Legends";
UPDATE finalHist SET logoPNG = "Louisville_Bats.png" WHERE tmName = "Louisville Bats";
UPDATE finalHist SET logoPNG = "Louisville_Redbirds.png" WHERE tmName = "Louisville Redbirds";
UPDATE finalHist SET logoPNG = "Louisville_RiverBats.png" WHERE tmName = "Louisville RiverBats";
UPDATE finalHist SET logoPNG = "Lowell_Spinners.png" WHERE tmName = "Lowell Spinners";
UPDATE finalHist SET logoPNG = "Lynchburg_Hillcats.png" WHERE tmName = "Lynchburg Hillcats";
UPDATE finalHist SET logoPNG = "Macon_Braves.png" WHERE tmName = "Macon Braves";
UPDATE finalHist SET logoPNG = "Mahoning_Valley_Scrappers.png" WHERE tmName = "Mahoning Valley Scrappers";
UPDATE finalHist SET logoPNG = "Maine_Guides.png" WHERE tmName = "Maine Guides";
UPDATE finalHist SET logoPNG = "Maine_Phillies.png" WHERE tmName = "Maine Phillies";
UPDATE finalHist SET logoPNG = "Memphis_Redbirds.png" WHERE tmName = "Memphis Redbirds";
UPDATE finalHist SET logoPNG = "México_Diablos_Rojos.png" WHERE tmName = "México Diablos Rojos";
UPDATE finalHist SET logoPNG = "Michigan_Battle_Cats.png" WHERE tmName = "Michigan Battle Cats";
UPDATE finalHist SET logoPNG = "Midland_RockHounds.png" WHERE tmName = "Midland RockHounds";
UPDATE finalHist SET logoPNG = "Minatitlán_Petroleros.png" WHERE tmName = "Minatitlán Petroleros";
UPDATE finalHist SET logoPNG = "Mississippi_Braves.png" WHERE tmName = "Mississippi Braves";
UPDATE finalHist SET logoPNG = "Missoula_Osprey.png" WHERE tmName = "Missoula Osprey";
UPDATE finalHist SET logoPNG = "Mobile_BayBears.png" WHERE tmName = "Mobile BayBears";
UPDATE finalHist SET logoPNG = "Modesto_A's.png" WHERE tmName = "Modesto A's";
UPDATE finalHist SET logoPNG = "Modesto_Nuts.png" WHERE tmName = "Modesto Nuts";
UPDATE finalHist SET logoPNG = "Monclova_Acereros.png" WHERE tmName = "Monclova Acereros";
UPDATE finalHist SET logoPNG = "Monterrey_Sultanes.png" WHERE tmName = "Monterrey Sultanes";
UPDATE finalHist SET logoPNG = "Montgomery_Biscuits.png" WHERE tmName = "Montgomery Biscuits";
UPDATE finalHist SET logoPNG = "Mudville_Nine.png" WHERE tmName = "Mudville Nine";
UPDATE finalHist SET logoPNG = "Myrtle_Beach_Pelicans.png" WHERE tmName = "Myrtle Beach Pelicans";
UPDATE finalHist SET logoPNG = "Nashville_Sounds.png" WHERE tmName = "Nashville Sounds";
UPDATE finalHist SET logoPNG = "New_Britain_Red_Sox.png" WHERE tmName = "New Britain Red Sox";
UPDATE finalHist SET logoPNG = "New_Britain_Rock_Cats.png" WHERE tmName = "New Britain Rock Cats";
UPDATE finalHist SET logoPNG = "New_Hampshire_Fisher_Cats.png" WHERE tmName = "New Hampshire Fisher Cats";
UPDATE finalHist SET logoPNG = "New_Haven_Ravens.png" WHERE tmName = "New Haven Ravens";
UPDATE finalHist SET logoPNG = "New_Jersey_Cardinals.png" WHERE tmName = "New Jersey Cardinals";
UPDATE finalHist SET logoPNG = "New_Orleans_Baby_Cakes.png" WHERE tmName = "New Orleans Baby Cakes";
UPDATE finalHist SET logoPNG = "New_Orleans_Zephyrs.png" WHERE tmName = "New Orleans Zephyrs";
UPDATE finalHist SET logoPNG = "Norfolk_Tides.png" WHERE tmName = "Norfolk Tides";
UPDATE finalHist SET logoPNG = "Northwest_Arkansas_Naturals.png" WHERE tmName = "Northwest Arkansas Naturals";
UPDATE finalHist SET logoPNG = "Norwich_Navigators.png" WHERE tmName = "Norwich Navigators";
UPDATE finalHist SET logoPNG = "Oaxaca_Guerreros.png" WHERE tmName = "Oaxaca Guerreros";
UPDATE finalHist SET logoPNG = "Ogden_Raptors.png" WHERE tmName = "Ogden Raptors";
UPDATE finalHist SET logoPNG = "Oklahoma_City_89ers.png" WHERE tmName = "Oklahoma City 89ers";
UPDATE finalHist SET logoPNG = "Oklahoma_City_Dodgers.png" WHERE tmName = "Oklahoma City Dodgers";
UPDATE finalHist SET logoPNG = "Oklahoma_City_RedHawks.png" WHERE tmName = "Oklahoma City RedHawks";
UPDATE finalHist SET logoPNG = "Oklahoma_Redhawks.png" WHERE tmName = "Oklahoma Redhawks";
UPDATE finalHist SET logoPNG = "Omaha_Golden_Spikes.png" WHERE tmName = "Omaha Golden Spikes";
UPDATE finalHist SET logoPNG = "Omaha_Royals.png" WHERE tmName = "Omaha Royals";
UPDATE finalHist SET logoPNG = "Omaha_Storm_Chasers.png" WHERE tmName = "Omaha Storm Chasers";
UPDATE finalHist SET logoPNG = "Oneonta_Tigers.png" WHERE tmName = "Oneonta Tigers";
UPDATE finalHist SET logoPNG = "Orem_Owlz.png" WHERE tmName = "Orem Owlz";
UPDATE finalHist SET logoPNG = "Orlando_Rays.png" WHERE tmName = "Orlando Rays";
UPDATE finalHist SET logoPNG = "Ottawa_Athletics.png" WHERE tmName = "Ottawa Athletics";
UPDATE finalHist SET logoPNG = "Ottawa_Lynx.png" WHERE tmName = "Ottawa Lynx";
UPDATE finalHist SET logoPNG = "Palm_Beach_Cardinals.png" WHERE tmName = "Palm Beach Cardinals";
UPDATE finalHist SET logoPNG = "Pawtucket_Red_Sox.png" WHERE tmName = "Pawtucket Red Sox";
UPDATE finalHist SET logoPNG = "Pensacola_Blue_Wahoos.png" WHERE tmName = "Pensacola Blue Wahoos";
UPDATE finalHist SET logoPNG = "Peoria_Chiefs.png" WHERE tmName = "Peoria Chiefs";
UPDATE finalHist SET logoPNG = "Piedmont_Boll_Weevils.png" WHERE tmName = "Piedmont Boll Weevils";
UPDATE finalHist SET logoPNG = "Pittsfield_Astros.png" WHERE tmName = "Pittsfield Astros";
UPDATE finalHist SET logoPNG = "Pittsfield_Mets.png" WHERE tmName = "Pittsfield Mets";
UPDATE finalHist SET logoPNG = "Portland_Beavers.png" WHERE tmName = "Portland Beavers";
UPDATE finalHist SET logoPNG = "Portland_Sea_Dogs.png" WHERE tmName = "Portland Sea Dogs";
UPDATE finalHist SET logoPNG = "Potomac_Cannons.png" WHERE tmName = "Potomac Cannons";
UPDATE finalHist SET logoPNG = "Potomac_Nationals.png" WHERE tmName = "Potomac Nationals";
UPDATE finalHist SET logoPNG = "Princeton_Devil_Rays.png" WHERE tmName = "Princeton Devil Rays";
UPDATE finalHist SET logoPNG = "Princeton_Rays.png" WHERE tmName = "Princeton Rays";
UPDATE finalHist SET logoPNG = "Puebla_Pericos.png" WHERE tmName = "Puebla Pericos";
UPDATE finalHist SET logoPNG = "Pulaski_Blue_Jays.png" WHERE tmName = "Pulaski Blue Jays";
UPDATE finalHist SET logoPNG = "Pulaski_Mariners.png" WHERE tmName = "Pulaski Mariners";
UPDATE finalHist SET logoPNG = "Pulaski_Yankees.png" WHERE tmName = "Pulaski Yankees";
UPDATE finalHist SET logoPNG = "Quad_Cities_River_Bandits.png" WHERE tmName = "Quad Cities River Bandits";
UPDATE finalHist SET logoPNG = "Queens_Kings.png" WHERE tmName = "Queens Kings";
UPDATE finalHist SET logoPNG = "Quintana_Roo_Tigres.png" WHERE tmName = "Quintana Roo Tigres";
UPDATE finalHist SET logoPNG = "Rancho_Cucamonga_Quakes.png" WHERE tmName = "Rancho Cucamonga Quakes";
UPDATE finalHist SET logoPNG = "Reading_Fightin_Phils.png" WHERE tmName = "Reading Fightin Phils";
UPDATE finalHist SET logoPNG = "Reading_Phillies.png" WHERE tmName = "Reading Phillies";
UPDATE finalHist SET logoPNG = "Reno_Aces.png" WHERE tmName = "Reno Aces";
UPDATE finalHist SET logoPNG = "Reynosa_Broncos.png" WHERE tmName = "Reynosa Broncos";
UPDATE finalHist SET logoPNG = "Richmond_Braves.png" WHERE tmName = "Richmond Braves";
UPDATE finalHist SET logoPNG = "Richmond_Flying_Squirrels.png" WHERE tmName = "Richmond Flying Squirrels";
UPDATE finalHist SET logoPNG = "Rochester_Red_Wings.png" WHERE tmName = "Rochester Red Wings";
UPDATE finalHist SET logoPNG = "Rocky_Mountain_Vibes.png" WHERE tmName = "Rocky Mountain Vibes";
UPDATE finalHist SET logoPNG = "Rome_Braves.png" WHERE tmName = "Rome Braves";
UPDATE finalHist SET logoPNG = "Round_Rock_Express.png" WHERE tmName = "Round Rock Express";
UPDATE finalHist SET logoPNG = "Sacramento_River_Cats.png" WHERE tmName = "Sacramento River Cats";
UPDATE finalHist SET logoPNG = "Salem_Red_Sox.png" WHERE tmName = "Salem Red Sox";
UPDATE finalHist SET logoPNG = "Salem-Keizer_Volcanoes.png" WHERE tmName = "Salem-Keizer Volcanoes";
UPDATE finalHist SET logoPNG = "Salt_Lake_Bees.png" WHERE tmName = "Salt Lake Bees";
UPDATE finalHist SET logoPNG = "Salt_Lake_Stingers.png" WHERE tmName = "Salt Lake Stingers";
UPDATE finalHist SET logoPNG = "Saltillo_Saraperos.png" WHERE tmName = "Saltillo Saraperos";
UPDATE finalHist SET logoPNG = "San_Antonio_Missions.png" WHERE tmName = "San Antonio Missions";
UPDATE finalHist SET logoPNG = "San_Bernardino_Stampede.png" WHERE tmName = "San Bernardino Stampede";
UPDATE finalHist SET logoPNG = "San_Jose_Giants.png" WHERE tmName = "San Jose Giants";
UPDATE finalHist SET logoPNG = "Sarasota_Red_Sox.png" WHERE tmName = "Sarasota Red Sox";
UPDATE finalHist SET logoPNG = "Sarasota_Reds.png" WHERE tmName = "Sarasota Reds";
UPDATE finalHist SET logoPNG = "Savannah_Sand_Gnats.png" WHERE tmName = "Savannah Sand Gnats";
UPDATE finalHist SET logoPNG = "Shreveport_Swamp_Dragons.png" WHERE tmName = "Shreveport Swamp Dragons";
UPDATE finalHist SET logoPNG = "South_Bend_Cubs.png" WHERE tmName = "South Bend Cubs";
UPDATE finalHist SET logoPNG = "South_Bend_Silver_Hawks.png" WHERE tmName = "South Bend Silver Hawks";
UPDATE finalHist SET logoPNG = "Southern_Oregon_Timberjacks.png" WHERE tmName = "Southern Oregon Timberjacks";
UPDATE finalHist SET logoPNG = "Spokane_Indians.png" WHERE tmName = "Spokane Indians";
UPDATE finalHist SET logoPNG = "Springfield_Cardinals.png" WHERE tmName = "Springfield Cardinals";
UPDATE finalHist SET logoPNG = "St._Catharines_Blue_Jays.png" WHERE tmName = "St. Catharines Blue Jays";
UPDATE finalHist SET logoPNG = "St._Catharines_Stompers.png" WHERE tmName = "St. Catharines Stompers";
UPDATE finalHist SET logoPNG = "St._Lucie_Mets.png" WHERE tmName = "St. Lucie Mets";
UPDATE finalHist SET logoPNG = "State_College_Spikes.png" WHERE tmName = "State College Spikes";
UPDATE finalHist SET logoPNG = "Staten_Island_Yankees.png" WHERE tmName = "Staten Island Yankees";
UPDATE finalHist SET logoPNG = "Stockton_Ports.png" WHERE tmName = "Stockton Ports";
UPDATE finalHist SET logoPNG = "Syracuse_Chiefs.png" WHERE tmName = "Syracuse Chiefs";
UPDATE finalHist SET logoPNG = "Syracuse_Mets.png" WHERE tmName = "Syracuse Mets";
UPDATE finalHist SET logoPNG = "Syracuse_SkyChiefs.png" WHERE tmName = "Syracuse SkyChiefs";
UPDATE finalHist SET logoPNG = "Tabasco_Olmecas.png" WHERE tmName = "Tabasco Olmecas";
UPDATE finalHist SET logoPNG = "Tacoma_Rainiers.png" WHERE tmName = "Tacoma Rainiers";
UPDATE finalHist SET logoPNG = "Tampa_Tarpons.png" WHERE tmName = "Tampa Tarpons";
UPDATE finalHist SET logoPNG = "Tampa_Yankees.png" WHERE tmName = "Tampa Yankees";
UPDATE finalHist SET logoPNG = "Tennessee_Smokies.png" WHERE tmName = "Tennessee Smokies";
UPDATE finalHist SET logoPNG = "Tijuana_Potros.png" WHERE tmName = "Tijuana Potros";
UPDATE finalHist SET logoPNG = "Tijuana_Toros.png" WHERE tmName = "Tijuana Toros";
UPDATE finalHist SET logoPNG = "Toledo_Mud_Hens.png" WHERE tmName = "Toledo Mud Hens";
UPDATE finalHist SET logoPNG = "Toronto_Maple_Leafs.png" WHERE tmName = "Toronto Maple Leafs";
UPDATE finalHist SET logoPNG = "Trenton_Thunder.png" WHERE tmName = "Trenton Thunder";
UPDATE finalHist SET logoPNG = "Tri-City_Dust_Devils.png" WHERE tmName = "Tri-City Dust Devils";
UPDATE finalHist SET logoPNG = "Tri-City_Valleycats.png" WHERE tmName = "Tri-City Valleycats";
UPDATE finalHist SET logoPNG = "Tucson_Padres.png" WHERE tmName = "Tucson Padres";
UPDATE finalHist SET logoPNG = "Tucson_Sidewinders.png" WHERE tmName = "Tucson Sidewinders";
UPDATE finalHist SET logoPNG = "Tulsa_Drillers.png" WHERE tmName = "Tulsa Drillers";
UPDATE finalHist SET logoPNG = "Utica_Blue_Sox.png" WHERE tmName = "Utica Blue Sox";
UPDATE finalHist SET logoPNG = "Vancouver_Canadians.png" WHERE tmName = "Vancouver Canadians";
UPDATE finalHist SET logoPNG = "Veracruz_Rojos_del_Águila.png" WHERE tmName = "Veracruz Rojos del Águila";
UPDATE finalHist SET logoPNG = "Vermont_Expos.png" WHERE tmName = "Vermont Expos";
UPDATE finalHist SET logoPNG = "Vermont_Lake_Monsters.png" WHERE tmName = "Vermont Lake Monsters";
UPDATE finalHist SET logoPNG = "Vermont_Mariners.png" WHERE tmName = "Vermont Mariners";
UPDATE finalHist SET logoPNG = "Vermont_Reds.png" WHERE tmName = "Vermont Reds";
UPDATE finalHist SET logoPNG = "Vero_Beach_Devil_Rays.png" WHERE tmName = "Vero Beach Devil Rays";
UPDATE finalHist SET logoPNG = "Vero_Beach_Dodgers.png" WHERE tmName = "Vero Beach Dodgers";
UPDATE finalHist SET logoPNG = "Visalia_Rawhide.png" WHERE tmName = "Visalia Rawhide";
UPDATE finalHist SET logoPNG = "West_Michigan_Whitecaps.png" WHERE tmName = "West Michigan Whitecaps";
UPDATE finalHist SET logoPNG = "West_Tennessee_Diamond_Jaxx.png" WHERE tmName = "West Tennessee Diamond Jaxx";
UPDATE finalHist SET logoPNG = "West_Virginia_Black_Bears.png" WHERE tmName = "West Virginia Black Bears";
UPDATE finalHist SET logoPNG = "West_Virginia_Power.png" WHERE tmName = "West Virginia Power";
UPDATE finalHist SET logoPNG = "Wichita_Aeros.png" WHERE tmName = "Wichita Aeros";
UPDATE finalHist SET logoPNG = "Wichita_Wranglers.png" WHERE tmName = "Wichita Wranglers";
UPDATE finalHist SET logoPNG = "Williamsport_Crosscutters.png" WHERE tmName = "Williamsport Crosscutters";
UPDATE finalHist SET logoPNG = "Wilmington_Blue_Rocks.png" WHERE tmName = "Wilmington Blue Rocks";
UPDATE finalHist SET logoPNG = "Winston-Salem_Dash.png" WHERE tmName = "Winston-Salem Dash";
UPDATE finalHist SET logoPNG = "Winston-Salem_Warthogs.png" WHERE tmName = "Winston-Salem Warthogs";
UPDATE finalHist SET logoPNG = "Wisconsin_Timber_Rattlers.png" WHERE tmName = "Wisconsin Timber Rattlers";
UPDATE finalHist SET logoPNG = "Yakima_Bears.png" WHERE tmName = "Yakima Bears";
UPDATE finalHist SET logoPNG = "Yucatán_Leones.png" WHERE tmName = "Yucatán Leones;