UPDATE newMinors SET logoPNG = "Aberdeen_IronBirds.png" WHERE team = "Aberdeen IronBirds";
UPDATE newMinors SET logoPNG = "Aguascalientes_Rieleros.png" WHERE team = "Aguascalientes Rieleros";
UPDATE newMinors SET logoPNG = "Akron_Aeros.png" WHERE team = "Akron Aeros";
UPDATE newMinors SET logoPNG = "Akron_RubberDucks.png" WHERE team = "Akron RubberDucks";
UPDATE newMinors SET logoPNG = "Albany-Colonie_Yankees.png" WHERE team = "Albany-Colonie Yankees";
UPDATE newMinors SET logoPNG = "Albuquerque_Dukes.png" WHERE team = "Albuquerque Dukes";
UPDATE newMinors SET logoPNG = "Albuquerque_Isotopes.png" WHERE team = "Albuquerque Isotopes";
UPDATE newMinors SET logoPNG = "Altoona_Curve.png" WHERE team = "Altoona Curve";
UPDATE newMinors SET logoPNG = "Amarillo_Sod_Poodles.png" WHERE team = "Amarillo Sod Poodles";
UPDATE newMinors SET logoPNG = "Arkansas_Travelers.png" WHERE team = "Arkansas Travelers";
UPDATE newMinors SET logoPNG = "Asheville_Tourists.png" WHERE team = "Asheville Tourists";
UPDATE newMinors SET logoPNG = "Auburn_Doubledays.png" WHERE team = "Auburn Doubledays";
UPDATE newMinors SET logoPNG = "Augusta_Greenjackets.png" WHERE team = "Augusta Greenjackets";
UPDATE newMinors SET logoPNG = "Bakersfield_Blaze.png" WHERE team = "Bakersfield Blaze";
UPDATE newMinors SET logoPNG = "Batavia_Muckdogs.png" WHERE team = "Batavia Muckdogs";
UPDATE newMinors SET logoPNG = "Beloit_Snappers.png" WHERE team = "Beloit Snappers";
UPDATE newMinors SET logoPNG = "Billings_Mustangs.png" WHERE team = "Billings Mustangs";
UPDATE newMinors SET logoPNG = "Biloxi_Shuckers.png" WHERE team = "Biloxi Shuckers";
UPDATE newMinors SET logoPNG = "Binghamton_Mets.png" WHERE team = "Binghamton Mets";
UPDATE newMinors SET logoPNG = "Binghamton_Rumble_Ponies.png" WHERE team = "Binghamton Rumble Ponies";
UPDATE newMinors SET logoPNG = "Birmingham_Barons.png" WHERE team = "Birmingham Barons";
UPDATE newMinors SET logoPNG = "Bluefield_Blue_Jays.png" WHERE team = "Bluefield Blue Jays";
UPDATE newMinors SET logoPNG = "Bluefield_Orioles.png" WHERE team = "Bluefield Orioles";
UPDATE newMinors SET logoPNG = "Boise_Hawks.png" WHERE team = "Boise Hawks";
UPDATE newMinors SET logoPNG = "Bowie_BaySox.png" WHERE team = "Bowie BaySox";
UPDATE newMinors SET logoPNG = "Bowling_Green_Hot_Rods.png" WHERE team = "Bowling Green Hot Rods";
UPDATE newMinors SET logoPNG = "Bradenton_Marauders.png" WHERE team = "Bradenton Marauders";
UPDATE newMinors SET logoPNG = "Brevard_County_Manatees.png" WHERE team = "Brevard County Manatees";
UPDATE newMinors SET logoPNG = "Bristol_Pirates.png" WHERE team = "Bristol Pirates";
UPDATE newMinors SET logoPNG = "Bristol_White_Sox.png" WHERE team = "Bristol White Sox";
UPDATE newMinors SET logoPNG = "Brooklyn_Cyclones.png" WHERE team = "Brooklyn Cyclones";
UPDATE newMinors SET logoPNG = "Buffalo_Bisons.png" WHERE team = "Buffalo Bisons";
UPDATE newMinors SET logoPNG = "Buies_Creek_Astros.png" WHERE team = "Buies Creek Astros";
UPDATE newMinors SET logoPNG = "Burlington_Bees.png" WHERE team = "Burlington Bees";
UPDATE newMinors SET logoPNG = "Burlington_Royals.png" WHERE team = "Burlington Royals";
UPDATE newMinors SET logoPNG = "Calgary_Cannons.png" WHERE team = "Calgary Cannons";
UPDATE newMinors SET logoPNG = "Campeche_Piratas.png" WHERE team = "Campeche Piratas";
UPDATE newMinors SET logoPNG = "Canton-Akron_Indians.png" WHERE team = "Canton-Akron Indians";
UPDATE newMinors SET logoPNG = "Capital_City_Bombers.png" WHERE team = "Capital City Bombers";
UPDATE newMinors SET logoPNG = "Carmen_Delfines.png" WHERE team = "Carmen Delfines";
UPDATE newMinors SET logoPNG = "Carolina_Mudcats.png" WHERE team = "Carolina Mudcats";
UPDATE newMinors SET logoPNG = "Casper_Ghosts.png" WHERE team = "Casper Ghosts";
UPDATE newMinors SET logoPNG = "Casper_Rockies.png" WHERE team = "Casper Rockies";
UPDATE newMinors SET logoPNG = "Cedar_Rapids_Kernels.png" WHERE team = "Cedar Rapids Kernels";
UPDATE newMinors SET logoPNG = "Charleston_Alley_Cats.png" WHERE team = "Charleston Alley Cats";
UPDATE newMinors SET logoPNG = "Charleston_Charlies.png" WHERE team = "Charleston Charlies";
UPDATE newMinors SET logoPNG = "Charleston_Riverdogs.png" WHERE team = "Charleston Riverdogs";
UPDATE newMinors SET logoPNG = "Charlotte_Knights.png" WHERE team = "Charlotte Knights";
UPDATE newMinors SET logoPNG = "Charlotte_Rangers.png" WHERE team = "Charlotte Rangers";
UPDATE newMinors SET logoPNG = "Charlotte_StoneCrabs.png" WHERE team = "Charlotte StoneCrabs";
UPDATE newMinors SET logoPNG = "Chattanooga_Lookouts.png" WHERE team = "Chattanooga Lookouts";
UPDATE newMinors SET logoPNG = "Chihuahua_Dorados.png" WHERE team = "Chihuahua Dorados";
UPDATE newMinors SET logoPNG = "Clearwater_Threshers.png" WHERE team = "Clearwater Threshers";
UPDATE newMinors SET logoPNG = "Clinton_Lumberkings.png" WHERE team = "Clinton Lumberkings";
UPDATE newMinors SET logoPNG = "Colorado_Springs_Sky_Sox.png" WHERE team = "Colorado Springs Sky Sox";
UPDATE newMinors SET logoPNG = "Columbia_Fireflies.png" WHERE team = "Columbia Fireflies";
UPDATE newMinors SET logoPNG = "Columbus_Catfish.png" WHERE team = "Columbus Catfish";
UPDATE newMinors SET logoPNG = "Columbus_Clippers.png" WHERE team = "Columbus Clippers";
UPDATE newMinors SET logoPNG = "Columbus_Jets.png" WHERE team = "Columbus Jets";
UPDATE newMinors SET logoPNG = "Columbus_RedStixx.png" WHERE team = "Columbus RedStixx";
UPDATE newMinors SET logoPNG = "Connecticut_Defenders.png" WHERE team = "Connecticut Defenders";
UPDATE newMinors SET logoPNG = "Connecticut_Tigers.png" WHERE team = "Connecticut Tigers";
UPDATE newMinors SET logoPNG = "Corpus_Christi_Hooks.png" WHERE team = "Corpus Christi Hooks";
UPDATE newMinors SET logoPNG = "Danville_97s.png" WHERE team = "Danville 97s";
UPDATE newMinors SET logoPNG = "Danville_Braves.png" WHERE team = "Danville Braves";
UPDATE newMinors SET logoPNG = "Dayton_Dragons.png" WHERE team = "Dayton Dragons";
UPDATE newMinors SET logoPNG = "Daytona_Cubs.png" WHERE team = "Daytona Cubs";
UPDATE newMinors SET logoPNG = "Daytona_Tortugas.png" WHERE team = "Daytona Tortugas";
UPDATE newMinors SET logoPNG = "Delmarva_Shorebirds.png" WHERE team = "Delmarva Shorebirds";
UPDATE newMinors SET logoPNG = "Denver_Zephyrs.png" WHERE team = "Denver Zephyrs";
UPDATE newMinors SET logoPNG = "Down_East_Wood_Ducks.png" WHERE team = "Down East Wood Ducks";
UPDATE newMinors SET logoPNG = "Dunedin_Blue_Jays.png" WHERE team = "Dunedin Blue Jays";
UPDATE newMinors SET logoPNG = "Durham_Bulls.png" WHERE team = "Durham Bulls";
UPDATE newMinors SET logoPNG = "Edmonton_Trappers.png" WHERE team = "Edmonton Trappers";
UPDATE newMinors SET logoPNG = "El_Paso_Chihuahuas.png" WHERE team = "El Paso Chihuahuas";
UPDATE newMinors SET logoPNG = "El_Paso_Diablos.png" WHERE team = "El Paso Diablos";
UPDATE newMinors SET logoPNG = "Elizabethton_Twins.png" WHERE team = "Elizabethton Twins";
UPDATE newMinors SET logoPNG = "Erie_SeaWolves.png" WHERE team = "Erie SeaWolves";
UPDATE newMinors SET logoPNG = "Eugene_Emeralds.png" WHERE team = "Eugene Emeralds";
UPDATE newMinors SET logoPNG = "Evansville_Triplets.png" WHERE team = "Evansville Triplets";
UPDATE newMinors SET logoPNG = "Everett_AquaSox.png" WHERE team = "Everett AquaSox";
UPDATE newMinors SET logoPNG = "Fayetteville_Woodpeckers.png" WHERE team = "Fayetteville Woodpeckers";
UPDATE newMinors SET logoPNG = "Florida_Fire_Frogs.png" WHERE team = "Florida Fire Frogs";
UPDATE newMinors SET logoPNG = "Fort_Myers_Miracle.png" WHERE team = "Fort Myers Miracle";
UPDATE newMinors SET logoPNG = "Fort_Wayne_Tincaps.png" WHERE team = "Fort Wayne Tincaps";
UPDATE newMinors SET logoPNG = "Fort_Wayne_Wizards.png" WHERE team = "Fort Wayne Wizards";
UPDATE newMinors SET logoPNG = "Frederick_Keys.png" WHERE team = "Frederick Keys";
UPDATE newMinors SET logoPNG = "Fresno_Grizzlies.png" WHERE team = "Fresno Grizzlies";
UPDATE newMinors SET logoPNG = "Frisco_RoughRiders.png" WHERE team = "Frisco RoughRiders";
UPDATE newMinors SET logoPNG = "Grand_Junction_Rockies.png" WHERE team = "Grand Junction Rockies";
UPDATE newMinors SET logoPNG = "Great_Falls_Voyagers.png" WHERE team = "Great Falls Voyagers";
UPDATE newMinors SET logoPNG = "Great_Falls_White_Sox.png" WHERE team = "Great Falls White Sox";
UPDATE newMinors SET logoPNG = "Great_Lakes_Loons.png" WHERE team = "Great Lakes Loons";
UPDATE newMinors SET logoPNG = "Greeneville_Astros.png" WHERE team = "Greeneville Astros";
UPDATE newMinors SET logoPNG = "Greeneville_Reds.png" WHERE team = "Greeneville Reds";
UPDATE newMinors SET logoPNG = "Greensboro_Bats.png" WHERE team = "Greensboro Bats";
UPDATE newMinors SET logoPNG = "Greensboro_Grasshoppers.png" WHERE team = "Greensboro Grasshoppers";
UPDATE newMinors SET logoPNG = "Greensboro_Hornets.png" WHERE team = "Greensboro Hornets";
UPDATE newMinors SET logoPNG = "Greenville_Bombers.png" WHERE team = "Greenville Bombers";
UPDATE newMinors SET logoPNG = "Greenville_Braves.png" WHERE team = "Greenville Braves";
UPDATE newMinors SET logoPNG = "Greenville_Drive.png" WHERE team = "Greenville Drive";
UPDATE newMinors SET logoPNG = "Gwinnett_Braves.png" WHERE team = "Gwinnett Braves";
UPDATE newMinors SET logoPNG = "Gwinnett_Stripers.png" WHERE team = "Gwinnett Stripers";
UPDATE newMinors SET logoPNG = "Hagerstown_Suns.png" WHERE team = "Hagerstown Suns";
UPDATE newMinors SET logoPNG = "Hardware_City_Rock_Cats.png" WHERE team = "Hardware City Rock Cats";
UPDATE newMinors SET logoPNG = "Harrisburg_Senators.png" WHERE team = "Harrisburg Senators";
UPDATE newMinors SET logoPNG = "Hartford_Yard_Goats.png" WHERE team = "Hartford Yard Goats";
UPDATE newMinors SET logoPNG = "Helena_Brewers.png" WHERE team = "Helena Brewers";
UPDATE newMinors SET logoPNG = "Hickory_Crawdads.png" WHERE team = "Hickory Crawdads";
UPDATE newMinors SET logoPNG = "High_Desert_Mavericks.png" WHERE team = "High Desert Mavericks";
UPDATE newMinors SET logoPNG = "Hillsboro_Hops.png" WHERE team = "Hillsboro Hops";
UPDATE newMinors SET logoPNG = "Hudson_Valley_Renegades.png" WHERE team = "Hudson Valley Renegades";
UPDATE newMinors SET logoPNG = "Huntsville_Stars.png" WHERE team = "Huntsville Stars";
UPDATE newMinors SET logoPNG = "Idaho_Falls_Chukars.png" WHERE team = "Idaho Falls Chukars";
UPDATE newMinors SET logoPNG = "Indianapolis_Indians.png" WHERE team = "Indianapolis Indians";
UPDATE newMinors SET logoPNG = "Inland_Empire_66ers.png" WHERE team = "Inland Empire 66ers";
UPDATE newMinors SET logoPNG = "Iowa_Cubs.png" WHERE team = "Iowa Cubs";
UPDATE newMinors SET logoPNG = "Iowa_Oaks.png" WHERE team = "Iowa Oaks";
UPDATE newMinors SET logoPNG = "Jackson_Generals.png" WHERE team = "Jackson Generals";
UPDATE newMinors SET logoPNG = "Jacksonville_Expos.png" WHERE team = "Jacksonville Expos";
UPDATE newMinors SET logoPNG = "Jacksonville_Jumbo_Shrimp.png" WHERE team = "Jacksonville Jumbo Shrimp";
UPDATE newMinors SET logoPNG = "Jacksonville_Suns.png" WHERE team = "Jacksonville Suns";
UPDATE newMinors SET logoPNG = "Jamestown_Jammers.png" WHERE team = "Jamestown Jammers";
UPDATE newMinors SET logoPNG = "Johnson_City_Cardinals.png" WHERE team = "Johnson City Cardinals";
UPDATE newMinors SET logoPNG = "Jupiter_Hammerheads.png" WHERE team = "Jupiter Hammerheads";
UPDATE newMinors SET logoPNG = "Kane_County_Cougars.png" WHERE team = "Kane County Cougars";
UPDATE newMinors SET logoPNG = "Kannapolis_Intimidators.png" WHERE team = "Kannapolis Intimidators";
UPDATE newMinors SET logoPNG = "Kingsport_Mets.png" WHERE team = "Kingsport Mets";
UPDATE newMinors SET logoPNG = "Kinston_Indians.png" WHERE team = "Kinston Indians";
UPDATE newMinors SET logoPNG = "Laguna_Vaqueros.png" WHERE team = "Laguna Vaqueros";
UPDATE newMinors SET logoPNG = "Lake_County_Captains.png" WHERE team = "Lake County Captains";
UPDATE newMinors SET logoPNG = "Lake_Elsinore_Storm.png" WHERE team = "Lake Elsinore Storm";
UPDATE newMinors SET logoPNG = "Lakeland_Flying_Tigers.png" WHERE team = "Lakeland Flying Tigers";
UPDATE newMinors SET logoPNG = "Lakeland_Tigers.png" WHERE team = "Lakeland Tigers";
UPDATE newMinors SET logoPNG = "Lakewood_BlueClaws.png" WHERE team = "Lakewood BlueClaws";
UPDATE newMinors SET logoPNG = "Lancaster_Jethawks.png" WHERE team = "Lancaster Jethawks";
UPDATE newMinors SET logoPNG = "Lansing_Lugnuts.png" WHERE team = "Lansing Lugnuts";
UPDATE newMinors SET logoPNG = "Las_Vegas_51s.png" WHERE team = "Las Vegas 51s";
UPDATE newMinors SET logoPNG = "Las_Vegas_Aviators.png" WHERE team = "Las Vegas Aviators";
UPDATE newMinors SET logoPNG = "Lehigh_Valley_IronPigs.png" WHERE team = "Lehigh Valley IronPigs";
UPDATE newMinors SET logoPNG = "Lexington_Legends.png" WHERE team = "Lexington Legends";
UPDATE newMinors SET logoPNG = "Louisville_Bats.png" WHERE team = "Louisville Bats";
UPDATE newMinors SET logoPNG = "Louisville_Redbirds.png" WHERE team = "Louisville Redbirds";
UPDATE newMinors SET logoPNG = "Louisville_RiverBats.png" WHERE team = "Louisville RiverBats";
UPDATE newMinors SET logoPNG = "Lowell_Spinners.png" WHERE team = "Lowell Spinners";
UPDATE newMinors SET logoPNG = "Lynchburg_Hillcats.png" WHERE team = "Lynchburg Hillcats";
UPDATE newMinors SET logoPNG = "Macon_Braves.png" WHERE team = "Macon Braves";
UPDATE newMinors SET logoPNG = "Mahoning_Valley_Scrappers.png" WHERE team = "Mahoning Valley Scrappers";
UPDATE newMinors SET logoPNG = "Maine_Guides.png" WHERE team = "Maine Guides";
UPDATE newMinors SET logoPNG = "Maine_Phillies.png" WHERE team = "Maine Phillies";
UPDATE newMinors SET logoPNG = "Memphis_Redbirds.png" WHERE team = "Memphis Redbirds";
UPDATE newMinors SET logoPNG = "México_Diablos_Rojos.png" WHERE team = "México Diablos Rojos";
UPDATE newMinors SET logoPNG = "Michigan_Battle_Cats.png" WHERE team = "Michigan Battle Cats";
UPDATE newMinors SET logoPNG = "Midland_RockHounds.png" WHERE team = "Midland RockHounds";
UPDATE newMinors SET logoPNG = "Minatitlán_Petroleros.png" WHERE team = "Minatitlán Petroleros";
UPDATE newMinors SET logoPNG = "Mississippi_Braves.png" WHERE team = "Mississippi Braves";
UPDATE newMinors SET logoPNG = "Missoula_Osprey.png" WHERE team = "Missoula Osprey";
UPDATE newMinors SET logoPNG = "Mobile_BayBears.png" WHERE team = "Mobile BayBears";
UPDATE newMinors SET logoPNG = "Modesto_A's.png" WHERE team = "Modesto A's";
UPDATE newMinors SET logoPNG = "Modesto_Nuts.png" WHERE team = "Modesto Nuts";
UPDATE newMinors SET logoPNG = "Monclova_Acereros.png" WHERE team = "Monclova Acereros";
UPDATE newMinors SET logoPNG = "Monterrey_Sultanes.png" WHERE team = "Monterrey Sultanes";
UPDATE newMinors SET logoPNG = "Montgomery_Biscuits.png" WHERE team = "Montgomery Biscuits";
UPDATE newMinors SET logoPNG = "Mudville_Nine.png" WHERE team = "Mudville Nine";
UPDATE newMinors SET logoPNG = "Myrtle_Beach_Pelicans.png" WHERE team = "Myrtle Beach Pelicans";
UPDATE newMinors SET logoPNG = "Nashville_Sounds.png" WHERE team = "Nashville Sounds";
UPDATE newMinors SET logoPNG = "New_Britain_Red_Sox.png" WHERE team = "New Britain Red Sox";
UPDATE newMinors SET logoPNG = "New_Britain_Rock_Cats.png" WHERE team = "New Britain Rock Cats";
UPDATE newMinors SET logoPNG = "New_Hampshire_Fisher_Cats.png" WHERE team = "New Hampshire Fisher Cats";
UPDATE newMinors SET logoPNG = "New_Haven_Ravens.png" WHERE team = "New Haven Ravens";
UPDATE newMinors SET logoPNG = "New_Jersey_Cardinals.png" WHERE team = "New Jersey Cardinals";
UPDATE newMinors SET logoPNG = "New_Orleans_Baby_Cakes.png" WHERE team = "New Orleans Baby Cakes";
UPDATE newMinors SET logoPNG = "New_Orleans_Zephyrs.png" WHERE team = "New Orleans Zephyrs";
UPDATE newMinors SET logoPNG = "Norfolk_Tides.png" WHERE team = "Norfolk Tides";
UPDATE newMinors SET logoPNG = "Northwest_Arkansas_Naturals.png" WHERE team = "Northwest Arkansas Naturals";
UPDATE newMinors SET logoPNG = "Norwich_Navigators.png" WHERE team = "Norwich Navigators";
UPDATE newMinors SET logoPNG = "Oaxaca_Guerreros.png" WHERE team = "Oaxaca Guerreros";
UPDATE newMinors SET logoPNG = "Ogden_Raptors.png" WHERE team = "Ogden Raptors";
UPDATE newMinors SET logoPNG = "Oklahoma_City_89ers.png" WHERE team = "Oklahoma City 89ers";
UPDATE newMinors SET logoPNG = "Oklahoma_City_Dodgers.png" WHERE team = "Oklahoma City Dodgers";
UPDATE newMinors SET logoPNG = "Oklahoma_City_RedHawks.png" WHERE team = "Oklahoma City RedHawks";
UPDATE newMinors SET logoPNG = "Oklahoma_Redhawks.png" WHERE team = "Oklahoma Redhawks";
UPDATE newMinors SET logoPNG = "Omaha_Golden_Spikes.png" WHERE team = "Omaha Golden Spikes";
UPDATE newMinors SET logoPNG = "Omaha_Royals.png" WHERE team = "Omaha Royals";
UPDATE newMinors SET logoPNG = "Omaha_Storm_Chasers.png" WHERE team = "Omaha Storm Chasers";
UPDATE newMinors SET logoPNG = "Oneonta_Tigers.png" WHERE team = "Oneonta Tigers";
UPDATE newMinors SET logoPNG = "Orem_Owlz.png" WHERE team = "Orem Owlz";
UPDATE newMinors SET logoPNG = "Orlando_Rays.png" WHERE team = "Orlando Rays";
UPDATE newMinors SET logoPNG = "Ottawa_Athletics.png" WHERE team = "Ottawa Athletics";
UPDATE newMinors SET logoPNG = "Ottawa_Lynx.png" WHERE team = "Ottawa Lynx";
UPDATE newMinors SET logoPNG = "Palm_Beach_Cardinals.png" WHERE team = "Palm Beach Cardinals";
UPDATE newMinors SET logoPNG = "Pawtucket_Red_Sox.png" WHERE team = "Pawtucket Red Sox";
UPDATE newMinors SET logoPNG = "Pensacola_Blue_Wahoos.png" WHERE team = "Pensacola Blue Wahoos";
UPDATE newMinors SET logoPNG = "Peoria_Chiefs.png" WHERE team = "Peoria Chiefs";
UPDATE newMinors SET logoPNG = "Piedmont_Boll_Weevils.png" WHERE team = "Piedmont Boll Weevils";
UPDATE newMinors SET logoPNG = "Pittsfield_Astros.png" WHERE team = "Pittsfield Astros";
UPDATE newMinors SET logoPNG = "Pittsfield_Mets.png" WHERE team = "Pittsfield Mets";
UPDATE newMinors SET logoPNG = "Portland_Beavers.png" WHERE team = "Portland Beavers";
UPDATE newMinors SET logoPNG = "Portland_Sea_Dogs.png" WHERE team = "Portland Sea Dogs";
UPDATE newMinors SET logoPNG = "Potomac_Cannons.png" WHERE team = "Potomac Cannons";
UPDATE newMinors SET logoPNG = "Potomac_Nationals.png" WHERE team = "Potomac Nationals";
UPDATE newMinors SET logoPNG = "Princeton_Devil_Rays.png" WHERE team = "Princeton Devil Rays";
UPDATE newMinors SET logoPNG = "Princeton_Rays.png" WHERE team = "Princeton Rays";
UPDATE newMinors SET logoPNG = "Puebla_Pericos.png" WHERE team = "Puebla Pericos";
UPDATE newMinors SET logoPNG = "Pulaski_Blue_Jays.png" WHERE team = "Pulaski Blue Jays";
UPDATE newMinors SET logoPNG = "Pulaski_Mariners.png" WHERE team = "Pulaski Mariners";
UPDATE newMinors SET logoPNG = "Pulaski_Yankees.png" WHERE team = "Pulaski Yankees";
UPDATE newMinors SET logoPNG = "Quad_Cities_River_Bandits.png" WHERE team = "Quad Cities River Bandits";
UPDATE newMinors SET logoPNG = "Queens_Kings.png" WHERE team = "Queens Kings";
UPDATE newMinors SET logoPNG = "Quintana_Roo_Tigres.png" WHERE team = "Quintana Roo Tigres";
UPDATE newMinors SET logoPNG = "Rancho_Cucamonga_Quakes.png" WHERE team = "Rancho Cucamonga Quakes";
UPDATE newMinors SET logoPNG = "Reading_Fightin_Phils.png" WHERE team = "Reading Fightin Phils";
UPDATE newMinors SET logoPNG = "Reading_Phillies.png" WHERE team = "Reading Phillies";
UPDATE newMinors SET logoPNG = "Reno_Aces.png" WHERE team = "Reno Aces";
UPDATE newMinors SET logoPNG = "Reynosa_Broncos.png" WHERE team = "Reynosa Broncos";
UPDATE newMinors SET logoPNG = "Richmond_Braves.png" WHERE team = "Richmond Braves";
UPDATE newMinors SET logoPNG = "Richmond_Flying_Squirrels.png" WHERE team = "Richmond Flying Squirrels";
UPDATE newMinors SET logoPNG = "Rochester_Red_Wings.png" WHERE team = "Rochester Red Wings";
UPDATE newMinors SET logoPNG = "Rocky_Mountain_Vibes.png" WHERE team = "Rocky Mountain Vibes";
UPDATE newMinors SET logoPNG = "Rome_Braves.png" WHERE team = "Rome Braves";
UPDATE newMinors SET logoPNG = "Round_Rock_Express.png" WHERE team = "Round Rock Express";
UPDATE newMinors SET logoPNG = "Sacramento_River_Cats.png" WHERE team = "Sacramento River Cats";
UPDATE newMinors SET logoPNG = "Salem_Red_Sox.png" WHERE team = "Salem Red Sox";
UPDATE newMinors SET logoPNG = "Salem-Keizer_Volcanoes.png" WHERE team = "Salem-Keizer Volcanoes";
UPDATE newMinors SET logoPNG = "Salt_Lake_Bees.png" WHERE team = "Salt Lake Bees";
UPDATE newMinors SET logoPNG = "Salt_Lake_Stingers.png" WHERE team = "Salt Lake Stingers";
UPDATE newMinors SET logoPNG = "Saltillo_Saraperos.png" WHERE team = "Saltillo Saraperos";
UPDATE newMinors SET logoPNG = "San_Antonio_Missions.png" WHERE team = "San Antonio Missions";
UPDATE newMinors SET logoPNG = "San_Bernardino_Stampede.png" WHERE team = "San Bernardino Stampede";
UPDATE newMinors SET logoPNG = "San_Jose_Giants.png" WHERE team = "San Jose Giants";
UPDATE newMinors SET logoPNG = "Sarasota_Red_Sox.png" WHERE team = "Sarasota Red Sox";
UPDATE newMinors SET logoPNG = "Sarasota_Reds.png" WHERE team = "Sarasota Reds";
UPDATE newMinors SET logoPNG = "Savannah_Sand_Gnats.png" WHERE team = "Savannah Sand Gnats";
UPDATE newMinors SET logoPNG = "Shreveport_Swamp_Dragons.png" WHERE team = "Shreveport Swamp Dragons";
UPDATE newMinors SET logoPNG = "South_Bend_Cubs.png" WHERE team = "South Bend Cubs";
UPDATE newMinors SET logoPNG = "South_Bend_Silver_Hawks.png" WHERE team = "South Bend Silver Hawks";
UPDATE newMinors SET logoPNG = "Southern_Oregon_Timberjacks.png" WHERE team = "Southern Oregon Timberjacks";
UPDATE newMinors SET logoPNG = "Spokane_Indians.png" WHERE team = "Spokane Indians";
UPDATE newMinors SET logoPNG = "Springfield_Cardinals.png" WHERE team = "Springfield Cardinals";
UPDATE newMinors SET logoPNG = "St._Catharines_Blue_Jays.png" WHERE team = "St. Catharines Blue Jays";
UPDATE newMinors SET logoPNG = "St._Catharines_Stompers.png" WHERE team = "St. Catharines Stompers";
UPDATE newMinors SET logoPNG = "St._Lucie_Mets.png" WHERE team = "St. Lucie Mets";
UPDATE newMinors SET logoPNG = "State_College_Spikes.png" WHERE team = "State College Spikes";
UPDATE newMinors SET logoPNG = "Staten_Island_Yankees.png" WHERE team = "Staten Island Yankees";
UPDATE newMinors SET logoPNG = "Stockton_Ports.png" WHERE team = "Stockton Ports";
UPDATE newMinors SET logoPNG = "Syracuse_Chiefs.png" WHERE team = "Syracuse Chiefs";
UPDATE newMinors SET logoPNG = "Syracuse_Mets.png" WHERE team = "Syracuse Mets";
UPDATE newMinors SET logoPNG = "Syracuse_SkyChiefs.png" WHERE team = "Syracuse SkyChiefs";
UPDATE newMinors SET logoPNG = "Tabasco_Olmecas.png" WHERE team = "Tabasco Olmecas";
UPDATE newMinors SET logoPNG = "Tacoma_Rainiers.png" WHERE team = "Tacoma Rainiers";
UPDATE newMinors SET logoPNG = "Tampa_Tarpons.png" WHERE team = "Tampa Tarpons";
UPDATE newMinors SET logoPNG = "Tampa_Yankees.png" WHERE team = "Tampa Yankees";
UPDATE newMinors SET logoPNG = "Tennessee_Smokies.png" WHERE team = "Tennessee Smokies";
UPDATE newMinors SET logoPNG = "Tijuana_Potros.png" WHERE team = "Tijuana Potros";
UPDATE newMinors SET logoPNG = "Tijuana_Toros.png" WHERE team = "Tijuana Toros";
UPDATE newMinors SET logoPNG = "Toledo_Mud_Hens.png" WHERE team = "Toledo Mud Hens";
UPDATE newMinors SET logoPNG = "Toronto_Maple_Leafs.png" WHERE team = "Toronto Maple Leafs";
UPDATE newMinors SET logoPNG = "Trenton_Thunder.png" WHERE team = "Trenton Thunder";
UPDATE newMinors SET logoPNG = "Tri-City_Dust_Devils.png" WHERE team = "Tri-City Dust Devils";
UPDATE newMinors SET logoPNG = "Tri-City_Valleycats.png" WHERE team = "Tri-City Valleycats";
UPDATE newMinors SET logoPNG = "Tucson_Padres.png" WHERE team = "Tucson Padres";
UPDATE newMinors SET logoPNG = "Tucson_Sidewinders.png" WHERE team = "Tucson Sidewinders";
UPDATE newMinors SET logoPNG = "Tulsa_Drillers.png" WHERE team = "Tulsa Drillers";
UPDATE newMinors SET logoPNG = "Utica_Blue_Sox.png" WHERE team = "Utica Blue Sox";
UPDATE newMinors SET logoPNG = "Vancouver_Canadians.png" WHERE team = "Vancouver Canadians";
UPDATE newMinors SET logoPNG = "Veracruz_Rojos_del_Águila.png" WHERE team = "Veracruz Rojos del Águila";
UPDATE newMinors SET logoPNG = "Vermont_Expos.png" WHERE team = "Vermont Expos";
UPDATE newMinors SET logoPNG = "Vermont_Lake_Monsters.png" WHERE team = "Vermont Lake Monsters";
UPDATE newMinors SET logoPNG = "Vermont_Mariners.png" WHERE team = "Vermont Mariners";
UPDATE newMinors SET logoPNG = "Vermont_Reds.png" WHERE team = "Vermont Reds";
UPDATE newMinors SET logoPNG = "Vero_Beach_Devil_Rays.png" WHERE team = "Vero Beach Devil Rays";
UPDATE newMinors SET logoPNG = "Vero_Beach_Dodgers.png" WHERE team = "Vero Beach Dodgers";
UPDATE newMinors SET logoPNG = "Visalia_Rawhide.png" WHERE team = "Visalia Rawhide";
UPDATE newMinors SET logoPNG = "West_Michigan_Whitecaps.png" WHERE team = "West Michigan Whitecaps";
UPDATE newMinors SET logoPNG = "West_Tennessee_Diamond_Jaxx.png" WHERE team = "West Tennessee Diamond Jaxx";
UPDATE newMinors SET logoPNG = "West_Virginia_Black_Bears.png" WHERE team = "West Virginia Black Bears";
UPDATE newMinors SET logoPNG = "West_Virginia_Power.png" WHERE team = "West Virginia Power";
UPDATE newMinors SET logoPNG = "Wichita_Aeros.png" WHERE team = "Wichita Aeros";
UPDATE newMinors SET logoPNG = "Wichita_Wranglers.png" WHERE team = "Wichita Wranglers";
UPDATE newMinors SET logoPNG = "Williamsport_Crosscutters.png" WHERE team = "Williamsport Crosscutters";
UPDATE newMinors SET logoPNG = "Wilmington_Blue_Rocks.png" WHERE team = "Wilmington Blue Rocks";
UPDATE newMinors SET logoPNG = "Winston-Salem_Dash.png" WHERE team = "Winston-Salem Dash";
UPDATE newMinors SET logoPNG = "Winston-Salem_Warthogs.png" WHERE team = "Winston-Salem Warthogs";
UPDATE newMinors SET logoPNG = "Wisconsin_Timber_Rattlers.png" WHERE team = "Wisconsin Timber Rattlers";
UPDATE newMinors SET logoPNG = "Yakima_Bears.png" WHERE team = "Yakima Bears";
UPDATE newMinors SET logoPNG = "Yucatán_Leones.png" WHERE team = "Yucatán Leones"